## Aula sobre Pré-Processamento

In [2]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
#Média de compra por pessoa
df['compra_por_pessoa'] = df['total_bill'] / df['size']
#Relação da gorjeta por compra
df['porcentagem_gorjeta'] = df['tip'] / df['total_bill']
df.head()

,total_bill,tip,sex,smoker,day,time,size,compra_por_pessoa,porcentagem_gorjeta
0,16.99,1.01,Female,No,Sun,Dinner,2,8.495000,0.059447
1,10.34,1.66,Male,No,Sun,Dinner,3,3.446667,0.160542
2,21.01,3.50,Male,No,Sun,Dinner,3,7.003333,0.166587
3,23.68,3.31,Male,No,Sun,Dinner,2,11.840000,0.139780
4,24.59,3.61,Female,No,Sun,Dinner,4,6.147500,0.146808

In [14]:
#Transformação de variáveis categóricas
from sklearn.preprocessing import OrdinalEncoder
copia = df.copy()
#Nominal
df_encoder = pd.get_dummies(df['sex'])
df_encoder.head()

#Ordinal
ordinal = OrdinalEncoder(categories=[['Thur', 'Fri', 'Sat', 'Sun']])
df_encoder['day_encoder'] = ordinal.fit_transform(df[['day']])
df_encoder.head()

copia['day_encoder'] = df_encoder['day_encoder']
copia.head(20)

,total_bill,tip,sex,smoker,day,time,size,compra_por_pessoa,porcentagem_gorjeta,day_encoder
0,16.99,1.01,Female,No,Sun,Dinner,2,8.495000,0.059447,3.0
1,10.34,1.66,Male,No,Sun,Dinner,3,3.446667,0.160542,3.0
2,21.01,3.50,Male,No,Sun,Dinner,3,7.003333,0.166587,3.0
3,23.68,3.31,Male,No,Sun,Dinner,2,11.840000,0.139780,3.0
4,24.59,3.61,Female,No,Sun,Dinner,4,6.147500,0.146808,3.0
5,25.29,4.71,Male,No,Sun,Dinner,4,6.322500,0.186240,3.0
6,8.77,2.00,Male,No,Sun,Dinner,2,4.385000,0.228050,3.0
7,26.88,3.12,Male,No,Sun,Dinner,4,6.720000,0.116071,3.0
8,15.04,1.96,Male,No,Sun,Dinner,2,7.520000,0.130319,3.0
9,14.78,3.23,Male,No,Sun,Dinner,2,7.390000,0.218539,3.0
10,10.27,1.71,Male,No,Sun,Dinner,2,5.135000,0.166504,3.0
11,35.26,5.00,Female,No,Sun,Dinner,4,8.815000,0.141804,3.0
12,15.42,1.57,Male,No,Sun,Dinner,2,7.710000,0.101816,3.0
13,18.43,3.00,Male,No,Sun,Dinner,4,4.607500,0.162778,3.0
14,14.83,3.02,Female,No,Sun,Dinner,2,7.415000,0.203641,3.0
15,21.58,3.92,Male,No,Sun,Dinner,2,10.790000,0.181650,3.0
16,10.33,1.67,Female,No,Sun,Dinner,3,3.443333,0.161665,3.0
17,16.29,3.71,Male,No,Sun,Dinner,3,5.430000,0.227747,3.0
18,16.97,3.50,Female,No,Sun,Dinner,3,5.656667,0.206246,3.0
19,20.65,3.35,Male,No,Sat,Dinner,3,6.883333,0.162228,2.0

In [21]:
#Transformação de variáveis numéricas

from sklearn.preprocessing import StandardScaler, MinMaxScaler

#total = df['total_bill']
#tip = df['tip']
copia['total_std'] = StandardScaler().fit_transform(df[['total_bill']])
copia['tip_nor'] = MinMaxScaler().fit_transform(df[['tip']])
copia.head()

,total_bill,tip,sex,smoker,day,time,size,compra_por_pessoa,porcentagem_gorjeta,day_encoder,total_std,tip_nor
0,16.99,1.01,Female,No,Sun,Dinner,2,8.495000,0.059447,3.0,-0.314711,0.001111
1,10.34,1.66,Male,No,Sun,Dinner,3,3.446667,0.160542,3.0,-1.063235,0.073333
2,21.01,3.50,Male,No,Sun,Dinner,3,7.003333,0.166587,3.0,0.137780,0.277778
3,23.68,3.31,Male,No,Sun,Dinner,2,11.840000,0.139780,3.0,0.438315,0.256667
4,24.59,3.61,Female,No,Sun,Dinner,4,6.147500,0.146808,3.0,0.540745,0.290000